apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  labels:
    app: demo
spec:
  replicas: 3  # Nombre de réplicas de votre application (Pod)
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: DockerFile
        image: your-dockerhub-username/your-app-name:latest  # Remplacez par votre image Docker
        ports:
        - containerPort: 8080  # Port sur lequel votre application écoute
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  selector:
    app: demo
  ports:
    - protocol: TCP
      port: 80  # Port d'accès externe
      targetPort: 8080  # Port où l'application écoute dans le conteneur
  type: LoadBalancer  # Vous pouvez utiliser ClusterIP ou NodePort selon vos besoins
