spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/mydb
    username: myuser
    password: mypassword
  sql:
    init:
      mode: always

      spring:
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      password: # Si nécessaire